[self]
name = "tatuin"
version = "0.25.0"
description = "Task Aggregator TUI for N providers"
license = "MIT"
notices = ["Copyright Â© 2025 <copyright holders>"]
repository = "https://github.com/panter-dsd/tatuin"
